services:
  docs:
    image: larkon_local_docs
    container_name: larkon_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./larkon:/app/larkon:z
    ports:
      - '9000:9000'
    command: /start-docs
